all: auto lambda rvalue

auto:auto.cxx
	g++ -std=c++0x -g -o auto auto.cxx

lambda:lambda.cxx
	g++ -std=c++0x -g -o lambda lambda.cxx

rvalue:rvalue.cxx
	g++ -std=c++0x -g -o rvalue rvalue.cxx -lboost_date_time