all: auto lambda rvalue

auto:auto.cxx
	cl /EHsc auto.cxx
	
lambda:lambda.cxx
	cl /EHsc lambda.cxx

rvalue:rvalue.cxx
	cl /EHsc /MDd rvalue.cxx /Id:/boost-trunk /link /STACK:102400000 /LIBPATH:d:/boost-trunk/stage/lib